@HotelListing.Api_HostAddress = https://localhost:7246

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
   "id": 4,
  "name": "Hotel C4",
  "address": "Address C",
  "rating": 4.9

}

###

@id=2
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

@id=4
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
   "id": 4,
  "name": "Test Hotel C",
  "address": "Address C",
  "rating": 4
    
}

###
